# Generated by Django 6.0.7 on 2026-07-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_userface'),
    ]

    operations = [
        migrations.AddField(
            model_name='userface',
            name='face_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userface',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userface',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
